### ISSUE TITLE
Request setting custom hostName

### ISSUE THREAD

**Issue by DRSDavidSoft** [Networking-for-Arduino/EthernetENC#49]
Hi there, currently the hostname is hardcoded to ENC28J + the last three hex digits of the MAC address:

https://github.com/JAndrassy/EthernetENC/blame/master/src/Dhcp.cpp#L195-L201

I was wondering if it could be possible to set it to a custom value? Perhaps something akin to this PR that is for WIZnet's `Ethernet.h`?
https://github.com/arduino-libraries/Ethernet/pull/77

Great work BTW, I'm very impressed by how smooth this chip works. I didn't expect it to perform this good, so I appreciate your great library!

**Comment by JAndrassy** [comment]
do you want to transfer the change to EthernetENC (it has the same DhcpClass) and submit a PR?

**Comment by d2weber** [comment]
Didn't look at the code. But setting the hostname like this: `Ethernet.setHostname("myhostname");` before `Ethernet.begin(mac)` seems to work.

**Comment by JAndrassy** [comment]
I added setHostname  Oct 3, 2023
